### ISSUE TITLE
DIVISION-BY-ZERO in some cases on SLIME

### ISSUE THREAD

**Issue by vityok** [crategus/cl-cffi-gtk#15]
This issue was reported before as #6 but it still remains here. It is reproduced if you save some lisp program (like Example 2.2 from the tutorial) into a file and then load it into SLIME with C-c C-l key combination (`slime-load-file`). But, if you load the same file using load function:

``` lisp
(load "example.lisp")
```

then the problem is not reproduced.

I've got SLIME 2013-09-29 but I guess that this problem does not depend on SLIME version.

Even if it is not fixed I believe that this work-around is useful to know for newcomers.

**Comment by kuberlog** [comment]
Adding `(sb-int:set-floating-point-modes :traps nil)` to `~/.sbclrc` fixed the problem.

**Comment by anranyicheng** [comment]
The best solution is to reset gtk every time: (sb-int:set-floating-point-modes :traps nil)
https://github.com/anranyicheng/cl-cffi-gtk/commit/ab920ebb0ea4066e062ae4d26b5b86a77ab19c7f
