### ISSUE TITLE
 (gdk-cursor-new-from-name (gdk-display-get-default) ...) returns nil no matter what

### ISSUE THREAD

**Issue by stacksmith** [crategus/cl-cffi-gtk#48]
I tried names from `https://developer.gnome.org/gdk3/stable/gdk3-Cursors.html#gdk-cursor-new-from-name` with no luck.  NIL always.

**Comment by Ferada** [comment]
`(gdk-cursor-new-from-name (gdk-display-get-default) "default")` works for me. In what context are you running this?

**Comment by stacksmith** [comment]
Sadly no longer have the code that needed it...  I will try to check it when I get a chance; let's assume it works since it works for you!
