### ISSUE TITLE
GtkCellRendererText "edited" signal invoked incorrectly

### ISSUE THREAD

**Issue by stacksmith** [crategus/cl-cffi-gtk#49]
The handler receives a string containing the tree path of the item edited instead of a path object.

**Comment by Ferada** [comment]
But that's how it's defined in the documentation too, c.f. https://developer.gnome.org/gtk3/stable/GtkCellRendererText.html#GtkCellRendererText-edited.

**Comment by stacksmith** [comment]
My mistake.
