### ISSUE TITLE
g-idle-add-full binding has wrong type for PRIORITY

### ISSUE THREAD

**Issue by stacksmith** [crategus/cl-cffi-gtk#50]
Your code is `(priority :uint)`, whereas GDK documentation shows gint
```guint
g_idle_add_full (gint priority,
                 GSourceFunc function,
                 gpointer data,
                 GDestroyNotify notify);
```
See https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html

**Comment by Ferada** [comment]
I put a fix [here](https://github.com/Ferada/cl-cffi-gtk/commit/6a080f223f85d24086d599c69354db9eff92e5ea).

**Comment by stacksmith** [comment]
Thank you!

**Comment by stacksmith** [comment]
@ferada, are you planning to merge your fixes into the @crategus repo?

**Comment by Ferada** [comment]
If I could I would; I'm going to ask if I can get permissions or do maintenance officially I guess.
