### ISSUE TITLE
gtk-text-mark-new and (make-instance 'gtk-text-mark) crash immediately!

### ISSUE THREAD

**Issue by stacksmith** [crategus/cl-cffi-gtk#53]
I get memory fault errors on SBCL.  In addition I noticed that there are 6 of these:
```
(sbcl:6789): Gtk-CRITICAL **: gtk_text_buffer_get_iter_at_mark: assertion '!gtk_text_mark_get_deleted (mark)' failed
CORRUPTION WARNING in SBCL pid 6789(tid 140737289156352):
Memory fault at 0x81f4 (pc=0x7fffe312d6b0, sp=0x7ffff4204778)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
```
in the log.  Somehow someone attempts to get an iter on the new mark, as it is being created...

**Comment by Ferada** [comment]
In a fresh instance I can't get it to do that, not even in the text buffer demo, do you have a reproducible example for it?

**Comment by stacksmith** [comment]
Thank you @Ferada.  You are correct.  I must have done something very weird, as just quickloading the project I live in makes it gtk-text-mark-new not work!  Before closing, I will chase it down just in case it is something useful to others.

**Comment by stacksmith** [comment]
Gah! My fault - a fancy print-object doing  stupid things that were once helpful.  Thank you again.
