### ISSUE TITLE
 cl-cffi-gtk/gdk/gdk.event-structures.lisp  mis-spells 'touch-cancel' as 'touch-canel'

### ISSUE THREAD

**Issue by stacksmith** [crategus/cl-cffi-gtk#54]
In many places...

**Comment by Ferada** [comment]
Fixed here https://github.com/Ferada/cl-cffi-gtk/commit/a1bd4d7836ea252120adb3fdaecac5e1bff57897.

**Comment by stacksmith** [comment]
Thanks, @Ferada... Check out https://github.com/stacksmith/subtext when you get a chance.

**Comment by crategus** [comment]
The error is corrected.
