### ISSUE TITLE
Shouldn't gdk-event-button-state be a gdk-modifier-type instead of a :uint?

### ISSUE THREAD

**Issue by Ambrevar** [crategus/cl-cffi-gtk#74]
In gdk.event-structures.lisp, the GdkEvent declares most `state` to be gdk-modifier-type.
Except for the `touch` and button` states, but I don't understand why since they should also be a list of modifiers instead of a mask.

Is this a mistake?

**Comment by crategus** [comment]
You are right. Both implementations works, but it should be consistent. Therefore I have changed :uint to gdk-modifier-type at the approbriate places.
